Repository tcp19/tcp-grand-resume, pull requests merged in 2021-10, with the labels that each got.

#45 FIX: #31 Change textbox outline to black for better accessibility
  styles/globals.css
Labels: bug, good first issue, hacktoberfest-accepted, hacktoberfest

#44 Feat/popover confirmation
  components/Popover.js
  pages/sections/CVForm.js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#42 Feat cv preview
  package-lock.json
  package.json
  pages/_app.js
  pages/build-resume.js
  pages/index.js
  pages/sections/CVForm.js
  pages/sections/PreviewCV.js
  public/assets/default.png
  templates/default.js
  templates/index.js
  utils/capitalizeFirst.js
  utils/capitalizeFirst.test.js
  utils/dataPoints.js
  utils/printAsPdf.js
Labels: enhancement, hacktoberfest-accepted
